services:

  api:
    build: ./dockers/api
    ports:
      - 20410:8000
    depends_on:
      - mongo
    networks:
    - node-network
    volumes:
      - type: bind
        source: ./dockers/api
        target: /mmx_app
      - type: bind
        source: ./mmx
        target: /mmx_app/mmx

    # command: sh -c "python server.py"
    command: sh -c "watchmedo auto-restart -p \"*.py\" python server.py"


  scrape:
    build: ./dockers/scrape
    depends_on:
      - mongo
      - embed
    networks:
    - node-network
    volumes:
      - type: bind
        source: ./dockers/scrape
        target: /mmx_app/
      - type: bind
        source: ./mmx/
        target: /mmx_app/mmx/

    command: sh -c "python server.py"


  cluster:
    build: ./dockers/cluster
    depends_on:
      - mongo
    networks:
    - node-network
    volumes:
      - type: bind
        source: ./dockers/cluster
        target: /mmx_app/
      - type: bind
        source: ./mmx/
        target: /mmx_app/mmx/

    command: sh -c "python server.py"


  embed:
    build: ./dockers/embed
    ports:
      - 8001:8001
    networks:
    - node-network
    volumes:
      - type: bind
        source: ./dockers/embed
        target: /mmx_app
      - type: bind
        source: ./mmx/
        target: /mmx_app/mmx/

    # command: sh -c "python server.py"
    command: sh -c "watchmedo auto-restart -p \"*.py\" python server.py"


  mongo:
    image: 'mongo:latest'
    ports:
     - 27018:27017
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
